### ISSUE TITLE
Ability to Update Target Temp

### ISSUE THREAD

**Issue by lazyboy0172** [sopelj/hass-ember-mug-component#14]
I see in the readme that we're not able to get writing attributes to work yet, and separately that mugs can only connect to one device at a time and must be factory reset in order to connect to home assistant. So, does that mean it's completely impossible to change the target temp on a non-traveler mug? I prefer a lower temp than the default 135, but if I'm reading correctly, that's currently not possible? I'm not able to pair to HA, then add to phone to change target temp and then delete mug from phone? Nor am I able to set the target temp via HA?

Just wanted to make sure I'm understanding correctly or if there are any known workarounds for my baby mouth that likes a cooler coffee.

**Comment by sopelj** [comment]
That is an excellent point, and I do completely understand that. I, too, would like the temperature to be a bit cooler on my mug.
I know that used to be the case, however I'm not 100% certain it is still required. I'll give it a try and confirm. However, I do know that you will have issues if you have two devices connected to it at the same time (otherwise you'll get frequent disconnects). However, you might be able to set it up in the app, and then unpair your device from your phone and pair it with home assistant. I'll try and test it.

**Comment by sopelj** [comment]
Awesome! Thank you for making me double check. So, it does look like using the 0.4 beta which uses the new Bluetooth Integration, it does seem like you can set up your mug as you wish using the app, and then you can pair it with home assistant. And not only that, if the mug was set up in the app, the services I added in home assistant that I said don't work, work! 
So, I will update the documentation to not only say that it does work, but that it is the better method.  You can change the temp, name and colour from home assistant after this :) The only issue is you shouldn't use both at the same time, so after the setup on your phone, you need to either forget the device on there or at least turn off your Bluetooth so the two systems don't fight over the mug.

**Comment by lazyboy0172** [comment]
well isn't that nice, a successfully closed ticket and the only thing to update is the readme. That's wonderful news, thank you for testing and for confirming!
