### ISSUE TITLE
HA is not able to see Ember 2 mug. 

### ISSUE THREAD

**Issue by mahawana** [sopelj/hass-ember-mug-component#2]
Hello SopelJ, I wonder if you can shed some light on the issue I'm seeing...

I used this integration but I'm not able to connect to my Ember Mug 2. After reset, HA I see the entity "sensor.mo_s_ember_mug", but its state is unavailable.  In looking in the log file, I see this error message: 

       021-12-26 03:42:46 WARNING (MainThread) [custom_components.ember_mug] Failed to connect to C9:0F:59:D6:33:F9 after 10 tries. Will try again in 2min

the mac address shown in the error message is the one used in your description.  I was not sure if I can use the same MAC address (I could not verify it).   
(PS: as a data point, I'm able to see the mug from iphone). 

(fyi, my configuration is running on a laptop with Virtual Machine running HA version 2021.12.5 ). 

thank you in advance. Your help is much appreciated.

**Comment by sopelj** [comment]
Hi, sorry, no, you need to put the MAC address of your mug in the settings for your config.
If you put mine it will never be found. I'll update the `README` to try and make it a bit more clear. 

In the mean time, someone just asked me how to find it so, that might help you too. 
https://github.com/sopelj/hass-ember-mug-component/issues/1

Eventually I'd like to implement auto-discovery, but I haven't had time yet.

**Comment by mahawana** [comment]
Hello sopelj, 
thanks for the fast response, and the helpful pointer on how to get the MAC address. the instructions you provided were for Android. However, I'm using the iphone 12 with IOS 15.1. After using logical steps similar to the description you provided, the IOS could not provide this info. Furthermore,  searching the internet for such instructions for Iphone,  did not yield positive results neither.  

I finally resolved the issue by connecting the mug to another computer I have that is running windows 10.  So, I now have the MAC address of the Ember. 
Unfortunately, with the MAC on hand, even that did not work. further debug and isolation, I think there may be something unique in Windows 11 that may be causing a problem.  the HA is running on machine that is running Windows 11, so perhaps there is some unique in my environment that I have to look into (I arrived at that conclusion because, without relying on HA to connect to the device,  this computer could not discover the Ember mug even though it can easily discover other devices like: headset, speaker, etc...). 

At any rate, thank you for taking the time to answer my question.

**Comment by sopelj** [comment]
@mahawana I'm sorry you couldn't get it working. The Ember Mug is very finicky. It only seems to allow connections from one device and no it does now enter the standard pairing mode. If you hold down the button for a few seconds it starts blinking blue. However, in my tests it will not actually be detectable by new devices if it is already paired with another device.

The only way I have found to connect to it is to reset the device (hold down button until light goes blue, then yellow then red. Then it'll blink red twice and goes back to white). Then make sure to forget it on your phone and any other device what know what it is. Then enter pairing mode again. If should now show up in the list of devices.

There may be an issue running it in a VM too. Are you sure the Bluetooth device has been passed through to the VM? Home assistant needs to have access to it in order to pair. If you install the SSH/Terminal add-on you can go into a Linux shell and use `bluetoothctl` to see if you Bluetooth is working and if you see any devices.

**Comment by mahawana** [comment]
Hello @sopelj, I’ve gone thru your suggestions below, and I agree the device is rather finicky. 

 

As for HA and VM interaction, I eliminated this dependency by simply trying to connect my Windows 10 machine directly to Ember mug. I was successful with this experiment. This experiment demonstrated that Ember and my laptop can connect directly, without any dependency on any program. Then I carried this same experiment to the my platform that carry the HA (which runs Windows 11),  again without using HA, I attempted to connect the mug to my laptop but I was not successful. 

Therefore, I concluded that there is a problem with my platform perhaps (which is totally independent of any program running on it). 

 

My next step is to try to resolve his problem (of direct connection between Windows and Ember), independent of HA. Once that is resolved, I can try the integration one more time.  

Meanwhile, I thank you for your support. 

 

Sincerely, 

Mohammed Hawana ***@***.***)

===================================================================

**Comment by leandrotoledo** [comment]
@sopelj thanks for this integration. I was only able to pair it with HA following the reset method you described, maybe it's worth to mention on `README.md`?

**Comment by sopelj** [comment]
@leandrotoledo I'm glad! I was hoping it wouldn't be necessary, but these comments and I have done done some more tests which seem to confirm it is. So, I will add it right way. Thanks for the suggestion!
